name: Build Release

on: 
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv sync

    - name: Run Windows Build Script
      run: .\build.bat

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: sims-saver-windows
        path: dist/sims-saver.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv sync

    - name: Run macOS Build Script
      run: chmod +x build.sh && ./build.sh

    - name: Upload macOS Application Bundle
      uses: actions/upload-artifact@v4
      with:
        name: sims-saver-macos
        path: dist/Sims4-Saver.app
